name: Setup Nox
description: "Prepares all python versions for nox"
inputs:
  python-versions:
    description: "List of python versions to install"
    required: true
    default: "['3.7', '3.8', '3.9', '3.10', 'pypy3.7', 'pypy3.8', 'pypy3.9']"
branding:
  icon: package
  color: blue

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: "pypy-2.7"
      if: ${{ contains(fromJSON(inputs.python-versions), 'pypy2.7') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "pypy-3.7"
      if: ${{ contains(fromJSON(inputs.python-versions), 'pypy3.7') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "pypy-3.8"
      if: ${{ contains(fromJSON(inputs.python-versions), 'pypy3.8') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "pypy-3.9"
      if: ${{ contains(fromJSON(inputs.python-versions), 'pypy3.9') }}

    - uses: actions/setup-python@v3
      with:
        python-version: "2.7"
      if: ${{ contains(fromJSON(inputs.python-versions), '2.7') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "3.4"
      if: ${{ contains(fromJSON(inputs.python-versions), '3.4') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "3.5"
      if: ${{ contains(fromJSON(inputs.python-versions), '3.5') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "3.6"
      if: ${{ contains(fromJSON(inputs.python-versions), '3.6') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "3.7"
      if: ${{ contains(fromJSON(inputs.python-versions), '3.7') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "3.8"
      if: ${{ contains(fromJSON(inputs.python-versions), '3.8') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
      if: ${{ contains(fromJSON(inputs.python-versions), '3.9') }}
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      # used to install nox
      # if: ${{ contains(fromJSON(inputs.python-versions), '3.10') }}

    - name: "Install nox"
      # --python "$(which python)" => always use the last setup-python version to install nox.
      run: pipx install --python "$(which python)" '${{ github.action_path }}'
      shell: bash
